### ISSUE TITLE
Set default to collapsed

### ISSUE THREAD

**Issue by psychemedia** [deshaw/jupyterlab-skip-traceback#17]
One very useful use case for the skip traceback extension is in educational settings, where verbose error traces are hidden from students unless they really want to see them.

Having to provide instructions to novice uses how to got into setting to effectively make use of the functionality of the extension is  a painful overhead, eg when writing explanatory text to get students started quickly.

If an educator is in control of a student environment, eg providing a predefined containerised environment, then default settings can be modified via a configuration file, but if students are using a "found" environment into which they have installed the extension themselves, they will be presented with the uncollapsed errors by default.

Is there a particularly strong reason for not enabling the collapsed state by default, escpecially give the extension is called `skip-traceback` not `optionally-skip-traceback`?

**Comment by tomazberisa** [comment]
Along these lines, is there a way to configure the default mode of the extension to display as collapsed?

**Comment by tomazberisa** [comment]
Answering my own question here for any others that may come across this issue:
1. Install `jupyterlab-skip-traceback` as usual (`pip install jupyterlab-skip-traceback`)
2. Update `~/.jupyter/lab/user-settings/jupyterlab-skip-traceback/settings.jupyterlab-settings` to contain:
```
{
    "collapsed": true
}
```
3. Restart Jupyter Lab

This can also be achieved by using the UI: Advanced Settings Editor -> Skip Traceback -> User Preferences.

Thank you @forestdussault
