### ISSUE TITLE
Does not yet support linking to paths (JupyterLab 4.1+)

### ISSUE THREAD

**Issue by krassowski** [deshaw/jupyterlab-skip-traceback#18]
The upcoming JupyterLab 4.1 will support linking to paths. `jupyterlab-skip-traceback` replaces `application/vnd.jupyter.error` renderer it disables linking. This is because JupyterLab 4.1 defines a new `renderError` function which enables opening files from tracebacks but `jupyterlab-skip-traceback` uses the old `renderText`:

https://github.com/deshaw/jupyterlab-skip-traceback/blob/b6cd79c02873a4e1cfd24a3fae5680a5f7adc0c8/src/SkipTracebackWidget.ts#L103

This will need to be swapped in a future version to support linking to paths.

**Comment by mlucool** [comment]
Fixed in https://github.com/deshaw/jupyterlab-skip-traceback/pull/20 and released in 5.1.0
