### ISSUE TITLE
The CI does not run on push to the default branch 

### ISSUE THREAD

**Issue by krassowski** [deshaw/jupyterlab-skip-traceback#19]
Since update to JupyterLab 4 the GitHub actions workflow is configured to run on `main`:

https://github.com/deshaw/jupyterlab-skip-traceback/blob/b6cd79c02873a4e1cfd24a3fae5680a5f7adc0c8/.github/workflows/build.yml#L5

but the default branch is still named `master`.

Would it be worth renaming the default branch to `main` or updating the workflow file?

**Comment by mlucool** [comment]
Renamed to main
