### ISSUE TITLE
update npm package repo

### ISSUE THREAD

**Issue by lneves12** [deshaw/jupyterlab-skip-traceback#21]
Hi!

is there any plans to update the version in NPM repository for this package? The latest version there is quite old: https://www.npmjs.com/package/jupyterlab-skip-traceback

Thank you!

Let me know if there is anything I can help with.

**Comment by mlucool** [comment]
No. Please use the python package: https://github.com/deshaw/jupyterlab-skip-traceback?tab=readme-ov-file#install
