### ISSUE TITLE
JupyterLab 3.0 update 

### ISSUE THREAD

**Issue by Jacques2101** [deshaw/jupyterlab-skip-traceback#6]
Hi, it seems that your extension is not compatible with version 3 of Jupyterlab. 
Thx for your help.

**Comment by mlucool** [comment]
Coming soon in https://github.com/deshaw/jupyterlab-skip-traceback/pull/8

**Comment by mlucool** [comment]
Published https://pypi.org/project/jupyterlab-skip-traceback/. Please let us know if you have any issues.
