### ISSUE TITLE
Traceback color does not match Neon Theme

### ISSUE THREAD

**Issue by ShahrokhBahtooei** [deshaw/jupyterlab-skip-traceback#7]
I use [Neon Theme](https://github.com/yeebc/jupyterlab-neon-theme). I would like to use _skip-traceback_ to experience short error messages too. But the different theme used in the add-on looks weird and uncomfortable to the eyes.

# Default error view on Neon Theme:
<img width="775" alt="Neon Theme default" src="https://user-images.githubusercontent.com/42028078/106886106-be909100-66f8-11eb-860b-79877bea211b.png">

---

# Skip-traceback (collapsed):
<img width="756" alt="Skip Tracebak (Collapsed)" src="https://user-images.githubusercontent.com/42028078/106886083-b8021980-66f8-11eb-92d6-0aab1b32a3f0.png">

- I dislike the red color on the error background.
- I wish the syntax coloring remained the same as the last line of traceback, i.e. something like this:
<img width="176" alt="Default last line for error" src="https://user-images.githubusercontent.com/42028078/106888340-aa01c800-66fb-11eb-823f-a9921fef499d.png">

---

# Skip-traceback (expanded):
<img width="734" alt="Skip Tracebak" src="https://user-images.githubusercontent.com/42028078/106886044-af114800-66f8-11eb-8335-44594814dad8.png">

- The red color on the error background is unwelcome to the eyes.

**Comment by mlucool** [comment]
This plugin works with the built-in two themes. That being said, we'd be happy to accept a PR that allows for this to either:
1. Work better in all themes
2. Allows more control to users/theme providers so it can be tailored to their needs

**Comment by mlucool** [comment]
Closing as stale. Feel free to reopen
